### ISSUE TITLE
When to open your code?

### ISSUE THREAD

**Issue by chensiyuan030105** [lzhnb/Analytic-Splatting#1]
I am looking forward for your implementation!

**Comment by chensiyuan030105** [comment]
I have attempted to reproduce your paper's results, but the performance is unstable and the training speed is very slow. I suspect there might be issues with my implementation. I would like to refer to your official implementation for guidance. Thank you!

**Comment by lzhnb** [comment]
Thanks for your attention!
I am sorry to have kept you waiting for so long. We are going to release the code it before ECCV camera is ready.
